README.md

Found out that the helm install command syntax takes "--" instead of "-".

updated typos

---

README.md
centraldirectory/values.yaml
centralenduserregistry/values.yaml
centralledger/values.yaml
update-charts-dep.sh

1. corrected description of values.yaml due to copy-pasta
2. updated readme.md to use "mojaloop" as the namespace
3. fixed issue in update-charts-dep.sh which was not updating central chart

Several updates

---

interop-switch/Chart.yaml
interop-switch/templates/config.yaml
interop-switch/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml

Link to issue:  https://github.com/mojaloop/helm/issues/66

Hotfix for issue #66

---

central/Chart.yaml
central/requirements.yaml
centraldirectory/Chart.yaml
centraldirectory/templates/config.yaml
centraldirectory/templates/deployment.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml

Bumped up mojaloop chart to version 3.4.2 to match hotfix release

Bumped up mojaloop chart to version 3.4.2 to match hotfix release

---

interop-switch/Chart.yaml
interop-switch/values.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

Fix for https://github.com/mojaloop/helm/issues/77

#77 Interop-switch chart has the incorrect configuration in values.yaml file for `ML_API_ADAPTER_PORT`

---

scripts/env.sh

updated fsp names

---

central/values.yaml
centralhub/values.yaml
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/values.yaml
centralledger/values.yaml
ml-api-adapter/Chart.yaml
ml-api-adapter/chart-handler-notification/Chart.yaml
ml-api-adapter/chart-handler-notification/templates/config.yaml
ml-api-adapter/chart-handler-notification/values.yaml
ml-api-adapter/chart-service/Chart.yaml
ml-api-adapter/chart-service/templates/config.yaml
ml-api-adapter/chart-service/values.yaml
ml-api-adapter/requirements.yaml
ml-api-adapter/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

fixes for values.yaml missing config to run the knex migrations

updates for deployment not populating the database or creating tables.

---

README.md

Improved documentation on how to install Mojaloop with Minikube

Walkthrough on how to install with Minikube

---

central/Chart.yaml
central/requirements.yaml
central/values.yaml
centralhub/requirements.yaml
centralhub/values.yaml
centralledger/Chart.yaml
centralledger/chart-handler-admin-transfer/Chart.yaml
centralledger/chart-handler-admin-transfer/values.yaml
centralledger/chart-handler-timeout/Chart.yaml
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/Chart.yaml
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/Chart.yaml
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position/Chart.yaml
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/Chart.yaml
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/Chart.yaml
centralledger/chart-service/values.yaml
centralledger/requirements.yaml
centralledger/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

FIx for #108, issue with timeout handler; Upgrading central ledger to v3.9.0 (from v3.8.3)

Upgrading to 3.8.4

---

central/requirements.yaml
central/values.yaml
centralhub/Chart.yaml
centralhub/requirements.yaml
centralhub/values.yaml
centralledger/Chart.yaml
centralledger/chart-handler-admin-transfer/Chart.yaml
centralledger/chart-handler-admin-transfer/values.yaml
centralledger/chart-handler-timeout/Chart.yaml
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/Chart.yaml
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/Chart.yaml
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position/Chart.yaml
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/Chart.yaml
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/Chart.yaml
centralledger/chart-service/values.yaml
centralledger/requirements.yaml
centralledger/values.yaml
centralsettlement/Chart.yaml
centralsettlement/values.yaml
mojaloop/values.yaml

(making Hub ID, Name configurable) and upgrading chart versions

Adding config required for item #547

---

centralledger/chart-handler-admin-transfer/configs/default.json
centralledger/chart-handler-admin-transfer/values.yaml
centralledger/chart-handler-timeout/configs/default.json
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/configs/default.json
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/configs/default.json
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position/configs/default.json
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/configs/default.json
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/configs/default.json
centralledger/chart-service/values.yaml
ml-api-adapter/chart-handler-notification/configs/default.json
ml-api-adapter/chart-handler-notification/values.yaml
ml-api-adapter/chart-service/configs/default.json
ml-api-adapter/chart-service/values.yaml

PR for https://github.com/mojaloop/project/issues/577

#577 Performance Enhancement- align Kafka Configs

---

centraleventprocessor/configs/default.json
emailnotifier/configs/default.json

1. changed the client/group id for emailnotifier
2. changed the client/group id for central-event-processor

changed kafka client and group id for story #595

---

central/values.yaml
centralledger/chart-service/values.yaml
centralledger/values.yaml
mojaloop/values.yaml

Removed the following configs from the values for centralledger:
- admin_key
- admin_secret

Removed unused admin keys/secret

---

central/values.yaml
centralsettlement/Chart.yaml
centralsettlement/values.yaml
mojaloop/values.yaml
monitoring/METRICS.md
monitoring/README.md

- Added docs for Prometheus Metrics 
- Enabled metrics for MySQL
- Also updated central-settlements to 5.1.1 to match latest release

Hotfix for #601 bug

---

central/Chart.yaml
central/requirements.yaml
central/values.yaml
centralledger/Chart.yaml
centralledger/chart-handler-admin-transfer/Chart.yaml
centralledger/chart-handler-admin-transfer/values.yaml
centralledger/chart-handler-timeout/Chart.yaml
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/Chart.yaml
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/Chart.yaml
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position/Chart.yaml
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/Chart.yaml
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/Chart.yaml
centralledger/chart-service/values.yaml
centralledger/requirements.yaml
centralledger/values.yaml
ml-api-adapter/Chart.yaml
ml-api-adapter/chart-handler-notification/Chart.yaml
ml-api-adapter/chart-handler-notification/values.yaml
ml-api-adapter/chart-service/Chart.yaml
ml-api-adapter/chart-service/values.yaml
ml-api-adapter/requirements.yaml
ml-api-adapter/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

Helm release for 5.2.0

---

central/values.yaml
centralledger/values.yaml
mojaloop/values.yaml
monitoring/dashboards/mojaloop/dashboard-central-services.json
monitoring/dashboards/mojaloop/dashboard-ml-adapter.json
monitoring/dashboards/mojaloop/dashboard-simulators.json
monitoring/efk/Chart.yaml
monitoring/efk/values.yaml
simulator/Chart.yaml
simulator/templates/NOTES.txt
simulator/templates/_helpers.tpl
simulator/templates/config.yaml
simulator/templates/deployment.yaml
simulator/templates/ingress.yaml
simulator/templates/service.yaml
simulator/values.yaml

1. Updated elasticsearch/efk containers to 6.6.0
2. Added simulator helm chart
3. Bug-fixes for https://github.com/mojaloop/project/issues/601

Maintenance update and bugfix update

---

simulator/Chart.yaml
simulator/values.yaml

Fix for https://github.com/mojaloop/project/issues/659

Updated Simulator version from 5.1.0 to 5.2.0

---

documentation/Chart.yaml
documentation/templates/NOTES.txt
documentation/templates/_helpers.tpl
documentation/templates/certmanager.yaml
documentation/templates/deployment.yaml
documentation/templates/ingress.yaml
documentation/templates/service.yaml
documentation/values.yaml

Part of investigation for story https://github.com/mojaloop/project/issues/691

Added initial Helm chart for documentation v5.4.0

---

central/Chart.yaml
central/requirements.yaml
centralledger/Chart.yaml
centralledger/chart-handler-admin-transfer/Chart.yaml
centralledger/chart-handler-admin-transfer/configs/default.json
centralledger/chart-handler-timeout/Chart.yaml
centralledger/chart-handler-timeout/configs/default.json
centralledger/chart-handler-transfer-fulfil/Chart.yaml
centralledger/chart-handler-transfer-fulfil/configs/default.json
centralledger/chart-handler-transfer-get/Chart.yaml
centralledger/chart-handler-transfer-get/configs/default.json
centralledger/chart-handler-transfer-position/Chart.yaml
centralledger/chart-handler-transfer-position/configs/default.json
centralledger/chart-handler-transfer-prepare/Chart.yaml
centralledger/chart-handler-transfer-prepare/configs/default.json
centralledger/chart-service/Chart.yaml
centralledger/chart-service/configs/default.json
centralledger/requirements.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml

- added missing configs from default.json for each of the central-ledger handlers
- bumped up the helm version from 6.1.0 to 6.1.1

Adding missing configs for centralledger default.json

---

central/Chart.yaml
central/values.yaml
centralledger/Chart.yaml
centralledger/chart-handler-admin-transfer/Chart.yaml
centralledger/chart-handler-admin-transfer/values.yaml
centralledger/chart-handler-timeout/Chart.yaml
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/Chart.yaml
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/Chart.yaml
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position/Chart.yaml
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/Chart.yaml
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/Chart.yaml
centralledger/chart-service/values.yaml
centralledger/values.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml

- updated central-ledger appVersion and container tags to v6.2.2 to support quoting-service changes

Updating charts for central-ledger v6.2.2 release to support quoting-service changes

---

central/Chart.yaml
central/requirements.yaml
central/values.yaml
centralledger/Chart.yaml
centralledger/chart-handler-admin-transfer/Chart.yaml
centralledger/chart-handler-admin-transfer/values.yaml
centralledger/chart-handler-timeout/Chart.yaml
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/Chart.yaml
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/Chart.yaml
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position/Chart.yaml
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/Chart.yaml
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/Chart.yaml
centralledger/chart-service/values.yaml
centralledger/requirements.yaml
centralledger/values.yaml
ml-api-adapter/Chart.yaml
ml-api-adapter/chart-handler-notification/Chart.yaml
ml-api-adapter/chart-handler-notification/values.yaml
ml-api-adapter/chart-service/Chart.yaml
ml-api-adapter/chart-service/values.yaml
ml-api-adapter/requirements.yaml
ml-api-adapter/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

- Updated ml-api-adapter to v6.2.0
- Updated central-ledger to v6.2.4

release updates for ml-api-adapter & central-ledger

---

account-lookup-service/Chart.yaml
account-lookup-service/chart-admin/Chart.yaml
account-lookup-service/chart-admin/values.yaml
account-lookup-service/chart-service/Chart.yaml
account-lookup-service/chart-service/values.yaml
account-lookup-service/requirements.yaml
account-lookup-service/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

Updated account-lookup-service release v6.2.3-snapshot to fix for https://github.com/mojaloop/project/issues/785

Updated account-lookup-service release v6.2.3-snapshot

---

eventstreamprocessor/Chart.yaml
eventstreamprocessor/configs/default.json

- updated efk client field name in default.json
- updated apm field name in default.json
- bumped chart to v8.1.1 to reflect the above changes.

Fixed config for eventstreamprocessor

---

monitoring/promfana/Chart.yaml
monitoring/promfana/requirements.yaml
monitoring/promfana/values.yaml

- Upgraded Prometheus: v2.13.1; 
- Upgraded Grafana: v6.4.2

Upgraded Promfana Helm chart for monitoring

---

centraleventprocessor/configs/default.json

bugfix/1049 Amount Scale Config

---

eventstreamprocessor/Chart.yaml
eventstreamprocessor/configs/default.json
eventstreamprocessor/values.yaml

- Upgraded Event Stream Processor to app version v8.4.2-snapshot
- Added new config to Event Stream Processor for START_CRITERIA and END_CRITERIA

Upgraded eventstreamprocess for 8.4.0 release

---

eventstreamprocessor/values.yaml

added start and end criteria for timeout spans

added config values to resolve the issue with timeout trace

---

mojaloop/Chart.yaml
mojaloop/requirements.yaml
quoting-service/Chart.yaml
quoting-service/templates/config.yaml
quoting-service/templates/deployment.yaml
quoting-service/values.yaml

Currently the `rules.json` is hard coded in the code, This change will allow the user to supply a custom `rules.json` file via chart

supply rules.json via charts

---

quoting-service/configs/default.json
quoting-service/values.yaml

The SWITCH_ENDPOINT had incorrect value, fixed it

added switch endpoint

---

finance-portal/templates/deployment.yaml
finance-portal/templates/secrets.yaml
finance-portal/values.yaml

Some implementations may want to use JWT keys for their solutions. This feature enables them to add  private JWT via values for the service.

Add custom JWT keys to finance-portal service

---

finance-portal-settlement-management/Chart.yaml
finance-portal-settlement-management/templates/configmap.yaml
finance-portal-settlement-management/templates/deployment.yaml
finance-portal-settlement-management/templates/secrets.yaml
finance-portal-settlement-management/values.yaml
finance-portal/Chart.yaml
finance-portal/templates/deployment.yaml
finance-portal/templates/secrets.yaml
finance-portal/values.yaml
mojaloop/requirements.yaml

This change modifies the way that the db values are accessed, following the same method as in the other services. At the same time, the finance-portal backend image version has been updated.

organize db values for portal services and bump up version

---

finance-portal/values.yaml
mojaloop/values.yaml

Update finance-portal-ui from 9.1.5 -> 9.1.6
Update finance-portal-backend-service from 9.1.2 -> 9.1.3

update finance portal images version

---

finance-portal/values.yaml
mojaloop/values.yaml

This version retains react classnames in the built image. This enables
better end-to-end UI testing of the built artifact using these
classnames as UI element selectors.

Updated portal frontend image versions

---

account-lookup-service/chart-admin/configs/default-sidecar.json
account-lookup-service/chart-admin/templates/config.yaml
account-lookup-service/chart-admin/templates/deployment.yaml
account-lookup-service/chart-admin/values.yaml
account-lookup-service/chart-service/configs/default-sidecar.json
account-lookup-service/chart-service/templates/config.yaml
account-lookup-service/chart-service/templates/deployment.yaml
account-lookup-service/chart-service/values.yaml
account-lookup-service/values.yaml
mojaloop/values.yaml

- Integrate sidecar for ALS admin and API
- Resolve port conflict for sidecar
- Upgrade ALS to 9.4.4
- Validated in Dev2

#1112: Integrate sidecar for ALS

---

finance-portal/templates/configmap.yaml
finance-portal/templates/secrets.yaml
finance-portal/values.yaml
mojaloop/values.yaml

These changes conform with the latest updates in finance-portal-backend-service v9.4.4 which contain dynamically configured values in the configuration file https://github.com/mojaloop/finance-portal-backend-service/blob/master/src/config/config.js#L48
Tested on my local installation and the values got propagated properly in the target container.

Added dynamically configured environmental variables in finance-portal-backend-service for Azure Log Analytics

---

mojaloop-simulator/Chart.yaml
mojaloop-simulator/templates/config-jws-public-keys.yaml
mojaloop-simulator/templates/deployment.yaml
mojaloop-simulator/templates/ingress.yaml
mojaloop-simulator/templates/secret.yaml
mojaloop-simulator/templates/service.yaml
mojaloop-simulator/values.yaml

Exposes the new SDK test server endpoint.
Should also address https://github.com/mojaloop/helm/issues/296.
Edit: also, as a newer version of the SDK has different TLS configuration, I've updated the chart to reflect this.
Sorry about the mixed PR.

Added SDK test API. Changed type of various config items.

---

mojaloop-simulator/Chart.yaml
mojaloop-simulator/values.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml

- Upgraded mojaloop-simulator to v9.4.1
- Upgraded sdk-scheme-adapter to v10.1.0

Updates to Mojaloop-Simulator

---

bulk-centralledger/Chart.yaml
bulk-centralledger/chart-handler-bulk-transfer-fulfil/Chart.yaml
bulk-centralledger/chart-handler-bulk-transfer-fulfil/values.yaml
bulk-centralledger/chart-handler-bulk-transfer-prepare/Chart.yaml
bulk-centralledger/chart-handler-bulk-transfer-prepare/values.yaml
bulk-centralledger/chart-handler-bulk-transfer-processing/Chart.yaml
bulk-centralledger/chart-handler-bulk-transfer-processing/values.yaml
bulk-centralledger/values.yaml
central/Chart.yaml
central/values.yaml
centralledger/Chart.yaml
centralledger/chart-handler-admin-transfer/Chart.yaml
centralledger/chart-handler-admin-transfer/values.yaml
centralledger/chart-handler-timeout/Chart.yaml
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/Chart.yaml
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position/Chart.yaml
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/Chart.yaml
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/Chart.yaml
centralledger/chart-service/values.yaml
centralledger/values.yaml
mojaloop-bulk/Chart.yaml
mojaloop-bulk/values.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml

Upgraded Central-ledger to v10.1.1 to fix issue: https://github.com/mojaloop/project/issues/1373

Hotfix for https://github.com/mojaloop/project/issues/1373

---

account-lookup-service/Chart.yaml
account-lookup-service/chart-admin/Chart.yaml
account-lookup-service/chart-admin/values.yaml
account-lookup-service/chart-service/Chart.yaml
account-lookup-service/chart-service/configs/default.json
account-lookup-service/chart-service/templates/deployment.yaml
account-lookup-service/chart-service/templates/secret-jws.yaml
account-lookup-service/chart-service/values.yaml
account-lookup-service/requirements.yaml
account-lookup-service/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

Added support for JWS signing;
Removed a duplicate declaration in `values.yaml`;
Bumped account-lookup-service-api to 10.1.1.

Added support for JWS signing

---

account-lookup-service/Chart.yaml
account-lookup-service/chart-admin/Chart.yaml
account-lookup-service/chart-admin/configs/default.json
account-lookup-service/chart-admin/values.yaml
account-lookup-service/chart-service/Chart.yaml
account-lookup-service/chart-service/values.yaml
account-lookup-service/requirements.yaml
account-lookup-service/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

Updated ALS versions 
Fix for ALS Admin not starting for missing JWS config

updates and fixes for ALS and ALS admin

---

finance-portal/Chart.yaml
finance-portal/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

Bumped `finance-portal-ui` to `v10.4.0`.

Bumped `finance-portal-ui` to `v10.4.0`.

---

install-remote.sh

Add initial install-remote.sh

---

.circleci/publish_helm_charts.sh
package.sh

Merge _strictly_ after https://github.com/mojaloop/helm/pull/356

Fixed bug with packaging introduced by #354

---

ml-testing-toolkit/chart-cli/templates/_helpers.tpl
ml-testing-toolkit/chart-cli/templates/job.yaml
ml-testing-toolkit/chart-cli/values.yaml

Enabled Scheduling in TTK CLI through CronJob in K8s

Modified the testing toolkit CLI chart to enabled scheduling

---

centralsettlement/chart-service/templates/deployment.yaml
centralsettlement/chart-service/values.yaml

fix:the scripts folder path

---

bulk-api-adapter/chart-handler-notification/Chart.yaml
bulk-api-adapter/chart-handler-notification/values.yaml
bulk-api-adapter/chart-service/Chart.yaml
bulk-api-adapter/chart-service/values.yaml
bulk-api-adapter/values.yaml
ml-testing-toolkit-cli/Chart.yaml
ml-testing-toolkit-cli/values.yaml
ml-testing-toolkit/Chart.yaml
ml-testing-toolkit/chart-backend/Chart.yaml
ml-testing-toolkit/chart-backend/values.yaml
mojaloop-bulk/Chart.yaml
mojaloop-bulk/values.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml

1. Reverted Bulk-api-adapter from v11.1.1 to v11.1.0 (hotfix to v12.0.0 release) due to the issue [#2084](https://github.com/mojaloop/project/issues/2084)
2. TTK (Testing-Toolkit) - Server logs are not displaying all the logs [#2065](https://github.com/mojaloop/project/issues/2065)
3. TTK CLI - Proper progress updates during test execution [#2008](https://github.com/mojaloop/project/issues/2008)

fix: hotfixes for v12.0.0 release

---

.circleci/config.yml
mojaloop/Chart.yaml
mojaloop/values.yaml

Added subId variables for TTK in values.yaml for https://github.com/mojaloop/project/issues/1636

feat: added subid variables for ttk in values yaml

---

ml-testing-toolkit-cli/Chart.yaml
ml-testing-toolkit-cli/values.yaml
ml-testing-toolkit/Chart.yaml
ml-testing-toolkit/chart-backend/Chart.yaml
ml-testing-toolkit/chart-backend/values.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml

feat: https://github.com/mojaloop/project/issues/2098

feat: upgrade to ml-testing-toolkit:v11.12.0

---

ml-testing-toolkit/chart-backend/values.yaml

- Disabled TTK backend keep-alive
ref: https://github.com/mojaloop/project/issues/2313

fix(v13.0.0): address testing toolkit connectivity stability issues

---

eventstreamprocessor/Chart.yaml
eventstreamprocessor/values.yaml

- upgraded event-stream-processor from v9.5.0 to v11.0.0
- bumped event-stream-process to v11 (based on version standards)

fix(release): v13.0.0-release.1

---

account-lookup-service/Chart.yaml
account-lookup-service/chart-admin/Chart.yaml
account-lookup-service/chart-admin/values.yaml
account-lookup-service/chart-service/Chart.yaml
account-lookup-service/chart-service/values.yaml
account-lookup-service/requirements.yaml
account-lookup-service/values.yaml
central/Chart.yaml
central/requirements.yaml
central/values.yaml
centralsettlement/Chart.yaml
centralsettlement/chart-service/Chart.yaml
centralsettlement/chart-service/values.yaml
centralsettlement/values.yaml
eventstreamprocessor/Chart.yaml
eventstreamprocessor/values.yaml
ml-testing-toolkit-cli/Chart.yaml
ml-testing-toolkit-cli/values.yaml
ml-testing-toolkit/Chart.yaml
ml-testing-toolkit/chart-backend/Chart.yaml
ml-testing-toolkit/chart-backend/values.yaml
ml-testing-toolkit/chart-frontend/Chart.yaml
ml-testing-toolkit/chart-frontend/values.yaml
ml-testing-toolkit/requirements.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

- bump to mojaloop helm chart to match patch version

feat(#2343): helm v13.0.1 release

---

.changelog/release-v13.1.0.md

- updated known issue
- fixed some typos/formatting issues
- added **BLOCKER PENDING** tag

chore: update release-v13.1.0 notes

---

.changelog/release-v13.1.0.md
.circleci/config.yml

- adding missing 'audit-licenses' requirement to deploy job (which was missing as a result of merging test + build jobs)
- updated release notes for v13.1.0 with updated revision table

chore: ci fixes and updated release notes

---

.changelog/release-v14.0.0.md
mojaloop-simulator/Chart.yaml
mojaloop-simulator/values.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml
thirdparty/values.yaml

- sdk-scheme-adapter: v11.18.11 -> **v18.0.2-snapshot.2** which includes fix for WS connecitivity

fix: ws connectivity stability issue

---

sdk-scheme-adapter/chart-service/values.yaml
sdk-scheme-adapter/values.yaml

- reworked sdk-scheme-adapter/chart-service to use Release.name for topic prefix's
- added config.simName for sdk-scheme-adapter values config
- updated configs to use config.simName for topic prefix's and DFSPID

feat: added config.simName for sdk-scheme-adapter

---

mojaloop-simulator/Chart.yaml
mojaloop-simulator/values.yaml
mojaloop-ttk-simulators/Chart.yaml
mojaloop-ttk-simulators/chart-sim1/Chart.yaml
mojaloop-ttk-simulators/chart-sim2/Chart.yaml
mojaloop-ttk-simulators/chart-sim3/Chart.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml
sdk-scheme-adapter/Chart.yaml
sdk-scheme-adapter/chart-service/Chart.yaml
sdk-scheme-adapter/chart-service/values.yaml
sdk-scheme-adapter/values.yaml
thirdparty/values.yaml

```
--------------------FINAL REPORT--------------------
Test Suite:Bulk Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 183                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 183                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 17                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 4                             │ …
```

chore: bump sdk

---

ml-testing-toolkit/Chart.yaml
ml-testing-toolkit/chart-frontend/Chart.yaml
ml-testing-toolkit/chart-frontend/values.yaml
mojaloop/Chart.yaml

fix([mojaloop/2995](https://github.com/mojaloop/project/issues/2995)): updated ttk-ui

fix(mojaloop/2995): update ttk-ui

---

account-lookup-service/chart-admin/values.yaml
account-lookup-service/chart-service/values.yaml
account-lookup-service/values.yaml
mojaloop/values.yaml

- fixed als api ingress service port fix from 4002/4001 to 80
- fixed formatting issues in for protocol_versions configs

fix: als-admin api ingress service port

---

.changelog/release-v14.0.0.md
ml-testing-toolkit/Chart.yaml
ml-testing-toolkit/chart-frontend/Chart.yaml
ml-testing-toolkit/chart-frontend/values.yaml
ml-testing-toolkit/requirements.yaml
mojaloop/Chart.yaml
mojaloop/requirements.yaml
mojaloop/values.yaml

fix(mojaloop/2995): update ttk-ui - https://github.com/mojaloop/project/issues/2995
- chore: bumped up ttk-ui
- updated v14.0.0 release notes
- chore: some change in appversion - Conflicts:
-	ml-testing-toolkit/Chart.yaml
-	ml-testing-toolkit/chart-frontend/Chart.yaml
-	mojaloop/Chart.yaml

fix(mojaloop/2995): update ttk-ui (#512)

---

mojaloop-simulator/Chart.yaml
mojaloop-simulator/values.yaml
mojaloop-ttk-simulators/Chart.yaml
mojaloop-ttk-simulators/chart-sim1/Chart.yaml
mojaloop-ttk-simulators/chart-sim2/Chart.yaml
mojaloop-ttk-simulators/chart-sim3/Chart.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml
sdk-scheme-adapter/Chart.yaml
sdk-scheme-adapter/chart-service/Chart.yaml
sdk-scheme-adapter/chart-service/values.yaml
sdk-scheme-adapter/values.yaml
thirdparty/values.yaml

- Bump version to new sdk-scheme-adapter release.
```
--------------------FINAL REPORT--------------------
Test Suite:Thirdparty Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 20                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 8 …
```

chore: bump sdk version

---

mojaloop-simulator/Chart.yaml
mojaloop-simulator/values.yaml
mojaloop-ttk-simulators/Chart.yaml
mojaloop-ttk-simulators/chart-sim1/Chart.yaml
mojaloop-ttk-simulators/chart-sim1/values.yaml
mojaloop-ttk-simulators/chart-sim2/Chart.yaml
mojaloop-ttk-simulators/chart-sim2/values.yaml
mojaloop-ttk-simulators/chart-sim3/Chart.yaml
mojaloop-ttk-simulators/chart-sim3/values.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml
sdk-scheme-adapter/Chart.yaml
sdk-scheme-adapter/chart-service/Chart.yaml
sdk-scheme-adapter/chart-service/values.yaml
sdk-scheme-adapter/values.yaml
thirdparty/values.yaml

- Bump sdk images
- Fix ttk urls

chore: update ttk urls

---

.changelog/release-v14.1.0.md
mojaloop-simulator/Chart.yaml
mojaloop-simulator/values.yaml
mojaloop-ttk-simulators/Chart.yaml
mojaloop-ttk-simulators/chart-sim1/Chart.yaml
mojaloop-ttk-simulators/chart-sim2/Chart.yaml
mojaloop-ttk-simulators/chart-sim3/Chart.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml
sdk-scheme-adapter/Chart.yaml
sdk-scheme-adapter/chart-service/Chart.yaml
sdk-scheme-adapter/chart-service/values.yaml
sdk-scheme-adapter/values.yaml
thirdparty/values.yaml

feat(mojaloop/3000): higher capacity bulk tests for load characterisation - https://github.com/mojaloop/project/issues/3000
- upgraded sdk-scheme-adapter to v12.3.2

feat(mojaloop/3000): higher capacity bulk tests for load characterisation

---

example-mojaloop-backend/values.yaml
ml-testing-toolkit-cli/Chart.yaml
ml-testing-toolkit-cli/templates/_helpers.tpl
ml-testing-toolkit-cli/values.yaml
ml-testing-toolkit/Chart.yaml
ml-testing-toolkit/chart-backend/Chart.yaml
ml-testing-toolkit/chart-backend/values.yaml
ml-testing-toolkit/chart-frontend/Chart.yaml
ml-testing-toolkit/chart-frontend/values.yaml
mojaloop-ttk-simulators/Chart.yaml
mojaloop-ttk-simulators/chart-sim1/Chart.yaml
mojaloop-ttk-simulators/chart-sim2/Chart.yaml
mojaloop-ttk-simulators/chart-sim3/Chart.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml

feat([mojaloop/3058](https://github.com/mojaloop/project/issues/3058)): enabled mongodb in ttk backend

feat(mojaloop/3058): enabled mongodb in ttk backend

---

.circleci/config.yml
.circleci/publish_helm_charts.sh

feat(mojaloop/#3073): add code to remove commited code from repo branch - https://github.com/mojaloop/project/issues/3073

feat(mojaloop/#3073): Remove committed code from gh-pages branch

---

.changelog/release-v15.0.0.md

- update v15 release notes with release date

chore: updated release notes [skip ci]

---

.changelog/release-v15.1.0.md
account-lookup-service/Chart.yaml
account-lookup-service/chart-admin/Chart.yaml
account-lookup-service/chart-admin/values.yaml
account-lookup-service/chart-service/Chart.yaml
account-lookup-service/chart-service/values.yaml
account-lookup-service/values.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml
transaction-requests-service/Chart.yaml
transaction-requests-service/values.yaml

- upgraded Account-Lookup from v14.0.0 to v14.1.0
- upgraded Transaction-Request-Service from v14.0.1 to v14.1.0
- updated v15.1.0 release notes
- bump to ALS charts

feat: updated services to support test currencies

---

monitoring/dashboards/mojaloop/dashboard-NodeJSApplication.json
monitoring/dashboards/mojaloop/dashboard-account-lookup-service.json
monitoring/dashboards/mojaloop/dashboard-central-services-characterization.json
monitoring/dashboards/mojaloop/dashboard-central-services.json
monitoring/dashboards/mojaloop/dashboard-ml-adapter.json

feat(mojaloop/#3416): update ml-api-adapter, nodejs and als dashboards - https://github.com/mojaloop/project/issues/3416
- Update dashboards
- Fix metric targets 
- Change deprecated graph visualizations to new time series visualization
- Add links to dashboard for grafana image exporting

feat(mojaloop/#3416): update cl, nodejs and als dashboards [skip ci]

---

quoting-service/configs/default.json
quoting-service/values.yaml

chore(mojaloop/#3565): update and validate cache change - https://github.com/mojaloop/project/issues/3565
Send Quote fail (SIM1 to SIM2) - POST - /quotes - [8/12]
Send quote - POST - /quotes - [1/2]
Test that fails due to `getParticipant` caching
Test that fails due to `getParticipantEndpoints` caching
[TTK-Assertion-Report-gp_tests_2023-10-18T20_47_02.132Z.zip](https://github.com/mojaloop/helm/files/13034862/TTK-Assertion-Report-gp_tests_2023-10-18T20_47_02.132Z.zip)

chore(mojaloop/#3565): update and validate cache change

---

sdk-scheme-adapter/chart-service/templates/deployment.yaml
sdk-scheme-adapter/chart-service/values.yaml

best practice would be to use k8s secrets for passing OAUTH_CLIENT_SECRET values.  this is first draft to add that to deployment

feat: support using k8s sec for OAUTH_CLIENT_SECRET

---

account-lookup-service/chart-admin/values.yaml
account-lookup-service/chart-service/values.yaml
account-lookup-service/values.yaml
ml-testing-toolkit/chart-backend/values.yaml
mojaloop/values.yaml

chore(mojaloop/#3759): update charts for fixing bug #3759 - https://github.com/mojaloop/project/issues/3759

chore(mojaloop/#3759): update charts for fixing bug #3759

---

monitoring/dashboards/mojaloop/dashboard-account-lookup-service.json
monitoring/dashboards/mojaloop/dashboard-central-services-characterization.json
monitoring/dashboards/mojaloop/dashboard-ml-adapter.json

Upgraded queries to filter data with respect to `cluster` label. This is useful for central-monitoring-environment.

feat: add cluster label to mojaloop dashboards

---

centralledger/chart-service/templates/migrate.yaml
centralledger/chart-service/templates/migration-job.yaml
centralledger/chart-service/values.yaml
centralledger/values.yaml
mojaloop/values.yaml

fix: move the migration from the init container to a job

---

LICENSE.md

- Updated the LICENSE.md file to the latest version. 
_this PR was automatically made by the __moja-tools-bot___

chore(moja-tools-bot): update license md file

---

.circleci/config.yml
.gitignore
centralledger/chart-handler-transfer-get/templates/deployment.yaml
eslint.config.mjs
inter-scheme-proxy-adapter/templates/deployment.yaml
lint-render.sh
ml-operator/templates/_helpers.tpl
ml-operator/templates/ml-operator.yaml
ml-operator/templates/operator-sevice-account.yaml
package-lock.json
package.json
thirdparty/chart-auth-svc/templates/deployment.yaml

A small error in the charts leads to ArgoCD failure to sync, breaking the continuous delivery process:
This PR improves linting with the following:
- Lint the rendered YAML using ESLint. Example output when the check fails:
The detailed report, which is available in the job artifacts includes details of the rendered file and the line with the error:
- Check the rendered YAML against k8s schema. Example output when the check fails:

feat: improve linting

---

mojaloop/templates/NOTES.txt

update notes and deployment guide link

chore: update notes and deployment guide link

---

.github/workflows/manifests/second-pass/account-lookup-service.yaml
.github/workflows/manifests/second-pass/mojaloop.yaml

fix: github release pr workflow

---

centralledger/Chart.yaml
centralledger/chart-handler-admin-transfer/Chart.yaml
centralledger/chart-handler-admin-transfer/values.yaml
centralledger/chart-handler-timeout/Chart.yaml
centralledger/chart-handler-timeout/values.yaml
centralledger/chart-handler-transfer-fulfil/Chart.yaml
centralledger/chart-handler-transfer-fulfil/values.yaml
centralledger/chart-handler-transfer-get/Chart.yaml
centralledger/chart-handler-transfer-get/values.yaml
centralledger/chart-handler-transfer-position-batch/Chart.yaml
centralledger/chart-handler-transfer-position-batch/values.yaml
centralledger/chart-handler-transfer-position/Chart.yaml
centralledger/chart-handler-transfer-position/values.yaml
centralledger/chart-handler-transfer-prepare/Chart.yaml
centralledger/chart-handler-transfer-prepare/values.yaml
centralledger/chart-service/Chart.yaml
centralledger/chart-service/values.yaml
centralledger/values.yaml
mojaloop/Chart.yaml
mojaloop/values.yaml

The knex migration script was failing while upgrading existing database. The fix is in central-ledger v19.4.3

fix: update central-ledger to fix knex migration script

---

sdk-scheme-adapter/chart-service/templates/deployment.yaml

Yarn + node 22 needs a writable temp directory

fix: fixes EROFS from Yarn + Node 22
