mojaloop/helm

central/requirements.yaml, central/values.yaml, centralhub/values.yaml, centralledger/Chart.yaml, centralledger/chart-handler-timeout/Chart.yaml, centralledger/chart-handler-timeout/values.yaml, centralledger/chart-handler-transfer-fulfil/Chart.yaml, centralledger/chart-handler-transfer-fulfil/values.yaml, centralledger/chart-handler-transfer-position/Chart.yaml, centralledger/chart-handler-transfer-position/values.yaml, centralledger/chart-handler-transfer-prepare/Chart.yaml, centralledger/chart-handler-transfer-prepare/values.yaml, centralledger/chart-handler-transfer-transfer/Chart.yaml, centralledger/chart-handler-transfer-transfer/values.yaml, centralledger/chart-service/Chart.yaml, centralledger/chart-service/values.yaml, centralledger/requirements.yaml, centralledger/values.yaml, mojaloop/values.yaml
Added fix to align container version in public configs for Central-ledger 3.5.1.
This has been verified for deployments on the following charts:
- centralledger
- central
- mojaloop
=> added fix to align container version in public configs

interop-switch/values.yaml, mojaloop/values.yaml
Removing duplicate keys defined in `values.yaml` for:
* emailnotifier
* interop-switch
=> fix: remove duplicate key definitions in values

centralledger/requirements.yaml
Updates the kafka requirement to the latest version
- Fixes bugs of values not being pulled through correctly
@mdebarros Can you try get this run against some nightly integration test to ensure it still passes? I did some manual testing my side and it looks to work correctly. This upgrade means zookeeper doesn't start a 3 node cluster when deploying mojaloop or centralledger. Which brings down the dev environment requirements quite considerably
**Before**
**After**
=> Update kafka requirement from 0.7.2 to 0.13.11

eventstreamprocessor/Chart.yaml, eventstreamprocessor/values.yaml, mojaloop/values.yaml
new event-stream-processor version, that handles sending of stale transfers to the APM Kibana dashboard, so they are not lost.
=> new event-stream-processor version

central/Chart.yaml, central/requirements.yaml, central/values.yaml, centraleventprocessor/Chart.yaml, centraleventprocessor/configs/default.json, centraleventprocessor/values.yaml, mojaloop/requirements.yaml, mojaloop/values.yaml
1. Port configs for centralledger were not updated to reflect that all service ports within k8s are now using 80 as standard
2. Removed unused central_ledger_api_host and central_ledger_api_port env vars/config that are deprecated
=> Fixes for centraleventprocessor

.circleci/config.yml, .circleci/upload-github-release-asset.sh
- Adds a script to automatically upload the license-summary.xlsx to a helm release as a part of the CI/CD process
I verified this manually with a temp release that I deleted from github afterwards.
=> Add license scanner file upload

finance-portal-settlement-management/templates/configmap.yaml, finance-portal-settlement-management/values.yaml, finance-portal/templates/configmap.yaml, finance-portal/values.yaml
This changes updates the finance portal helm charts so it follows the same `$release_name` convention. It also updates the version for the finance portal that fixes some SQL queries and containers versions.
=> update release-name in values and bump up versions

finance-portal/Chart.yaml, finance-portal/templates/configmap.yaml, finance-portal/values.yaml, mojaloop/Chart.yaml, mojaloop/requirements.yaml, mojaloop/values.yaml
Exposing this already existing-config:
https://github.com/mojaloop/finance-portal-backend-service/blob/master/src/config/config.js#L38
to the chart. That controls whether the service responds with an `Access-Control-Allow-Origin` header that mirrors the `Origin` header in the request. When it does so, it means a UI served to the browser from any hostname can make requests to the backend- not just one served from the same hostname as the backend. It's standard browser security functionality- nothing implementation-specific.
The specific use-case I'm trying to enable in this case is hosting a frontend on a developer machine and a backend in a cluster somewhere. I.e. frontend on localhost, backend on some other hostname.
=> Exposing the portal backend CORS reflect origin option to make local testing easier

finance-portal/templates/configmap.yaml, finance-portal/values.yaml, mojaloop/values.yaml
Covers the changes in finance-portal-backend-service that were applied through these PRs mojaloop/finance-portal-backend-service#27
mojaloop/finance-portal-backend-service#28
and have been released as v9.1.0
https://github.com/mojaloop/finance-portal-backend-service/releases/tag/v9.1.0
=>  Bump to finance-portal-backend v9.1.0

.circleci/publish_helm_charts.sh
Motivated by:
https://github.com/casablanca-project/helm/blob/gh-pages/mojaloop/Chart.yaml
It's possible to have a merge conflict arise but the modified script will simply commit the merge conflict to the repo. This change will cause said script to fail if there is a merge conflict.
=> Detecting merge conflicts in helm chart publish script

als-oracle-pathfinder/templates/deployment.yaml, als-oracle-pathfinder/values.yaml, mojaloop/values.yaml
Split the init containers enabling in order to control which will run and which not.
=> Added the ability to configure which init containers will run for the als-oracle-pathfinder

finance-portal-settlement-management/templates/deployment.yaml, mojaloop/values.yaml
New Mojaloop installations and upgrades will work with Helm2 and Helm3 with these PR changes:
- Fixed bad affinity, nodeSelector and toleration configs in the deployment template for settlement-management
- Maintenance: Removed duplicate keys (tolerations, affinity) from mojaloop values config
=> Fixes helm3 deployment issue

mojaloop-simulator/templates/ingress.yaml, mojaloop-simulator/values.yaml
With these defaults
- ingress is disabled by default
- if a user enables ingress but doesn't specify a host, they'll automatically receive a wildcard host
=> Added some more intuitive ingress defaults

CODEOWNERS, ml-api-adapter/Chart.yaml, ml-api-adapter/chart-handler-notification/Chart.yaml, ml-api-adapter/chart-handler-notification/values.yaml, ml-api-adapter/chart-service/Chart.yaml, ml-api-adapter/chart-service/values.yaml, ml-api-adapter/requirements.yaml, ml-api-adapter/values.yaml, mojaloop/Chart.yaml, mojaloop/requirements.yaml, mojaloop/values.yaml
**Summary:**
Upgraded the version of ml-api-adapter to `v10.3.1`. This includes a bugfix where `GET /transfers` notification was not signed by the switch
=> bugfix GET /transfers JWS issue

.circleci/config.yml, mojaloop-simulator/Chart.yaml, mojaloop-simulator/templates/deployment.yaml, mojaloop-simulator/templates/ingress.yaml, mojaloop-simulator/templates/secret.yaml, mojaloop-simulator/values.yaml, mojaloop/requirements.yaml, update-charts-dep.sh
Also generating only a single CA for automatic credential generation. Makes much more sense that all generated keys + certs should be signed by the same CA.
`update-chart-deps.sh`
- Modified to trap non-zero return codes and print the existing error message. The loop could be considered a matter of taste and if someone prefers the existing sequence of commands to the loop I wouldn't fight them to the death over it.
- Called by `bash` to support `trap ERR`.
=> Allow the user to supply their own TLS creds

mojaloop-simulator/templates/deployment.yaml
Note that these variable values corresponded very poorly with the mount path specified here: https://github.com/mojaloop/helm/pull/343/files#diff-dffddc6158ba2a6ec51607c2896a66afR93
=> Fixed default tls secret mount location config

mojaloop-simulator/templates/deployment.yaml, mojaloop-simulator/values.yaml
The default value was broken.
As can be seen here:
https://github.com/mojaloop/helm/blob/4afd91b4d4c976e1f8d60495c677f1ba48b30192/mojaloop-simulator/templates/deployment.yaml#L90
and here:
https://github.com/mojaloop/helm/blob/4afd91b4d4c976e1f8d60495c677f1ba48b30192/mojaloop-simulator/templates/secret.yaml#L22
the key is being placed at `/jwsSigningKey/private.key`. It is not possible to volume mount to root. The existing configuration may have appeared to be working because there's a key packaged in the image for testing purposes (I'm not certain of this, I haven't checked). I'm not convinced configuration of this option adds any value, so I commented it out. It is in fact still configurable, as values set in the `values.yaml` file will take precedence over those in …
=> JWS signing key default was broken.

monitoring/dashboards/kubernetes/Kubernetes Cluster.json
Calculates the memory usage % based on this suggestion: https://github.com/prometheus/node_exporter/issues/877
Example:
This PR updates just the single JSON field, but I'm a little worried the current dashboard is quite different than what is it checked in to git as.
=> Update 'System Services Memory Usage' to use node_exporter metrics

mojaloop/requirements.yaml, quoting-service/Chart.yaml, quoting-service/templates/config.yaml
With this addition the user of this chart can pass the rules as a helm template file and then consume it like this: `helm template . --set-file mojaloop.quoting-service.rules.template=<PATH-TO-RULES-FILE>`
=> Added the option to pass a template as the rules.json

.circleci/config.yml, .circleci/publish_helm_charts.sh
- upgrades circleci version to 2.1 to keep things more consistent with our other pipelines
- tidy up of the scripts and yaml templates
- fix an issue where the commit message for `gh_pages` was missing information
- move slack announcement to *git tags only*, so we don't get an empty alert every time there's a merge into master
Tested manually:
=> fix(ci): slack announcement

mojaloop-simulator/templates/deployment.yaml
**Bug:**
Getting the following error when deploying mojaloop helm chart
`Error: template: mojaloop/charts/mojaloop-simulator/templates/_helpers.tpl:56:22: executing "mojaloop-simulator.apiVersion.Deployment" at <.Capabilities.APIVersions.Has>: nil pointer evaluating interface {}.APIVersions`
**Fix:**
In the file _mojaloop-simulator/templates/deployment.yaml_
The template reference "mojaloop-simulator.apiVersion.Deployment" inside the "range" block should be called by passing the parent scope `('$')` instead of current scope `('.')` beacuse the range operator is changing the current scope.
=> Fixed the scope to pass for the template apiVersion.Deployment

mojaloop-simulator/templates/secret.yaml
Before this change, the following configuration will not work. Afterward, it will. This enables supply of a private JWS key secret by an external source.
```yaml
simulators:
payerfsp:
config:
schemeAdapter:
secrets:
jws:
privKeySecretName: hello
env:
JWS_SIGN: true
```
=> Fixed bug supplying external JWS private key secret

.changelog/release-v13.0.0.md, .changelog/release-v13.0.2.md, account-lookup-service/Chart.yaml, account-lookup-service/chart-admin/Chart.yaml, account-lookup-service/chart-admin/values.yaml, account-lookup-service/chart-service/Chart.yaml, account-lookup-service/chart-service/values.yaml, account-lookup-service/requirements.yaml, account-lookup-service/values.yaml, mojaloop/Chart.yaml, mojaloop/requirements.yaml, mojaloop/values.yaml, quoting-service/Chart.yaml, quoting-service/values.yaml
* chore: release v13.0.2
- Added release notes for v13.0.2
- Fixed typos in release notes v13.0.0, v13.0.1
- Added https://github.com/mojaloop/project/issues/2358 as a known issue to v13.0.1 release notes
- Upgraded Account-lookup-service from v11.7.0 to v11.7.2 -> fix for https://github.com/mojaloop/project/issues/2358
- Bump to Account-lookup-service helm chart
- Upgraded Quoting-service from v12.0.6 to v12.0.7 -> fix for https://github.com/mojaloop/project/issues/2358
- Bump to Quoting-service helm chart
- Bump to Mojaloop helm chart
=> chore: release v13.0.2

thirdparty/README.md, thirdparty/chart-auth-svc/Chart.yaml, thirdparty/chart-auth-svc/values.yaml, thirdparty/chart-consent-oracle/Chart.yaml, thirdparty/chart-consent-oracle/README.md, thirdparty/chart-consent-oracle/example_dependencies.yaml, thirdparty/chart-consent-oracle/templates/_helpers.tpl, thirdparty/chart-consent-oracle/templates/configmap.yaml, thirdparty/chart-consent-oracle/templates/deployment.yaml, thirdparty/chart-consent-oracle/templates/ingress.yaml, thirdparty/chart-consent-oracle/templates/service.yaml, thirdparty/chart-consent-oracle/values.yaml
PR 2/3 for the base Thirdparty charts
- Adds support for a Consent oracle type that the ALS can use to store the owner of the Consent object.
- Cleans up log level in the auth-svc charts
Part of mojaloop/project#2450
=> feat(thirdparty): add consent-oracle chart

.changelog/release-v13.1.0.md
- removed known issue **Mojaloop-Simulator Rules path requires a `$` prefix** as this is covered in detail within the release notes
- added `8.3 Bulk API Helm Tests` which includes a link to where more information can be attained on how to enable/use the bulk-api-adapter tests
=> chore: update release-v13.1.0.md notes

mojaloop-simulator/Chart.yaml, mojaloop-simulator/templates/deployment.yaml, mojaloop-simulator/values.yaml, mojaloop/Chart.yaml, mojaloop/requirements.yaml, mojaloop/values.yaml, thirdparty/Chart.yaml, thirdparty/README.md, thirdparty/values.yaml
Passing it as a yaml array wasn't working. I'm guessing you need to loop through it in the template but decided to keep it as such since the other `command` prompts in the template expect a string.
Tested on moja3.
```
--------------------FINAL REPORT--------------------
Test Suite:GP Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │ …
```
=> chore: bump and validate sdk-scheme-adapter api-svc

.changelog/release-v14.1.0.md
docs: update release-v14.1.0 notes [skip ci]
- added Known issue 10.4. [#3027 - QA: Mojaloop Helm v14.1.0 Release - Bulk Tests fail on first run](https://github.com/mojaloop/project/issues/3027)
=> docs: update release-v14.1.0 notes [skip ci]

mojaloop-ttk-simulators/chart-sim1/values.yaml, mojaloop-ttk-simulators/chart-sim2/values.yaml, mojaloop-ttk-simulators/chart-sim3/values.yaml, mojaloop/values.yaml
feat(mojaloop/#3023): sdk bulk CICD functional tests - https://github.com/mojaloop/project/issues/3023
- updated `rules_response_default.json` for TTK Sims 1,2 & 3 in mojaloop/values.yaml
- updated `rules_response_default.json` for TTK Sims 1,2 & 3 in each of the default chart-sim# values.yaml
- fixed formatting with mojaloop/values.yaml
Notes:
- The `rules_response_default.json` changes are a result of moving (and consolidating) the Rules from [testing-toolkit-test-cases](https://github.com/mojaloop/testing-toolkit-test-cases/pull/101) repo to the SDK-Scheme-Adapter repo.
=> feat(mojaloop/#3023): sdk bulk CICD functional tests

package.sh
- default repo URL in package.sh now points to github.io
=> chore: updated package.sh with default repo URL

.changelog/release-v14.1.0.md, .changelog/release-v14.1.1.md, .circleci/config.yml, .circleci/publish_helm_charts.sh, ml-testing-toolkit/Chart.yaml, ml-testing-toolkit/chart-backend/Chart.yaml, ml-testing-toolkit/chart-backend/templates/ingress.yaml, ml-testing-toolkit/chart-backend/values.yaml, ml-testing-toolkit/chart-connection-manager-backend/templates/ingress.yaml, ml-testing-toolkit/chart-connection-manager-backend/values.yaml, ml-testing-toolkit/chart-connection-manager-frontend/templates/ingress.yaml, ml-testing-toolkit/chart-connection-manager-frontend/values.yaml, ml-testing-toolkit/chart-frontend/Chart.yaml, ml-testing-toolkit/chart-frontend/templates/ingress.yaml, ml-testing-toolkit/chart-frontend/values.yaml, ml-testing-toolkit/chart-keycloak/templates/ingress.yaml, ml-testing-toolkit/chart-keycloak/values.yaml, mojaloop-ttk-simulators/Chart.yaml, mojaloop-ttk-simulators/chart-sim1/Chart.yaml, mojaloop-ttk-simulators/chart-sim1/values.yaml, mojaloop-ttk-simulators/chart-sim2/Chart.yaml, mojaloop-ttk-simulators/chart-sim2/values.yaml, mojaloop-ttk-simulators/chart-sim3/Chart.yaml, mojaloop-ttk-simulators/chart-sim3/values.yaml, mojaloop/Chart.yaml, mojaloop/values.yaml, package.sh, sdk-scheme-adapter/values.yaml
- Bump TTK charts
- Parametize ingress of hard coded charts
- Add prelimanary changelog outlining bug fixes and changes in TTK
Tested on moja5 using deploy-config files 
[values-moja5-test-mojaloop-backend-v14.1.1.yaml](https://github.com/mojaloop/deploy-config/blob/release/v14.1.1/mojaloop/test.mojaloop.live/values-moja5-test-mojaloop-backend-v14.1.1.yaml)
[chore: value files](https://github.com/mojaloop/deploy-config/commit/2143418377f350c9b17cf85aa08308453916bf67)
now
[values-moja5-test-mojaloop-harness-v14.1.1.yaml](https://github.com/mojaloop/deploy-config/blob/release/v14.1.1/mojaloop/test.mojaloop.live/values-moja5-test-mojaloop-harness-v14.1.1.yaml)
[chore: value files](https://github.com/mojaloop/deploy-config/commit/2143418377f350c9b17cf85aa08308453916bf67)
Tested against …
=> feat(mojaloop/#3127): parameterize ingress class name and bump versions

ml-testing-toolkit-cli/templates/_helpers.tpl
The exit code for test container is set always to success(0) because of the echo statement at the end.
=> fix: exit code for test container

.changelog/release-v15.0.1.md, ml-testing-toolkit-cli/Chart.yaml, ml-testing-toolkit-cli/templates/_helpers.tpl, ml-testing-toolkit-cli/templates/job.yaml, ml-testing-toolkit-cli/templates/tests/ttk-runner.yaml, ml-testing-toolkit-cli/values.yaml, mojaloop/Chart.yaml, mojaloop/values.yaml
feat(mojaloop/#3361): reset liquidity - https://github.com/mojaloop/project/issues/3361
- added`'ml-ttk-cronjob-cleanup` cron-job to main Mojaloop Helm chart
- made some improvements to the `ml-testing-toolkit-cli`
- parameterized: `restartPolicy`, `backoffLimit`, `successfulJobsHistoryLimit`, `failedJobsHistoryLimit`
- added cronJob configs for `suspend`, `timeZone` 
- fixed `imagePullSecrets` --> `pullSecrets` for consistency 
- moved command arguments to parameterized `script` value configuration to allow for configuration flexibility. 
- added support to configure `allowFailures` which allows for Helm Test failures to be ignored if set to `true`
- minor chart bump to `ml-testing-toolkit-cli` and `mojaloop` helm charts for patch release
- added initial release notes for v15.0.1 …
=> feat(mojaloop/#3361): reset liquidity

mojaloop/Chart.yaml
- fixes for miss-aligned versions in mojaloop/chart.yaml
=> chore: fixes to main chart application versions [skip ci]

.circleci/config.yml, example-mojaloop-backend/README.md
fix(mojaloop/#3392): circleCI slack notifications are failing - https://github.com/mojaloop/project/issues/3392
- removed slack-announcement job, and integrated it directly into publish job as per other mojaloop ci jobs
- cleaned example-mojaloop-backend readme - the instructions on how to configure the helm client is already linked in pre-requisites section
=> fix(mojaloop/#3392): circleCI slack notifications are failing

monitoring/dashboards/mojaloop/dashboard-account-lookup-service.json
feat(mojaloop/#3399): add initial als grafana dashboard - https://github.com/mojaloop/project/issues/3399
- Add initial grafana dashboard focusing solely on parties/participant ingress and domain logic performance
=> feat(mojaloop/#3399): add initial als grafana dashboard [skip ci]

.circleci/config.yml, monitoring/dashboards/kubernetes/Kubernetes Cluster.json, monitoring/dashboards/kubernetes/kubernetes-monitoring-dashboard.json
- Added PVC utiliztion chart
- updated title from `Kubernetes Cluster` to `Kubernetes Monitoring Dashboard`
- updated `uid` to avoid collision with old dashboard  and filename in git repo
- fixed POD related queries by removing `name="^k8s_*"` filter
=> fix: update k8s monitoring dashboard

monitoring/dashboards/mojaloop/dashboard-quoting-service.json
We are moving the dashboard from [mojaloop/ml-core-test-harness](https://github.com/mojaloop/ml-core-test-harness/blob/v1.2.4-snapshot.0/docker/grafana/provisioning/dashboards/mojaloop/dashboard-quoting-service.json) repo to [mojaloop/helm](https://github.com/mojaloop/helm) repo.
=> feat: added dashboard-quoting-service.json

monitoring/dashboards/mojaloop/dashboard-performance-troubleshooting.json
Following charts have been added to the dashboard
- Kafka: partitions by topic
- Kafka: consumers by consumer group
- Kafka: Lag by topic
- network util by node
- disk I/O rate by node
- network util by container
=> feat(#3994): update performance dashboard

account-lookup-service/chart-service/configs/default.json, account-lookup-service/chart-service/values.yaml, account-lookup-service/values.yaml, example-mojaloop-backend/Chart.yaml, example-mojaloop-backend/values.yaml, ml-api-adapter/chart-handler-notification/configs/default.json, ml-api-adapter/chart-handler-notification/values.yaml, ml-api-adapter/values.yaml, mojaloop/values.yaml, quoting-service/chart-handler/Chart.yaml, quoting-service/chart-handler/configs/default.json, quoting-service/chart-handler/values.yaml, quoting-service/chart-service/Chart.yaml, quoting-service/chart-service/values.yaml, quoting-service/values.yaml
https://github.com/mojaloop/project/issues/3991 
- Added proxy lib
- Added configuration for proxy
- Added unit and integration tests for proxy related functionalities
=> feat(mojaloop/#3991): add proxy cache config for quoting service and ml-api-adapter

example-mojaloop-backend/Chart.yaml, example-mojaloop-backend/values.yaml, mojaloop/Chart.yaml
Deployments using default configuration having handshake issues without this config when mojaloop is deployed on the backend following the instructions here: https://docs.mojaloop.io/technical/deployment-guide/#_5-mojaloop
This fixes it and has been tested a few times. Thanks to Vijay and the FX PR
=> fix: changes to kafka config to add protocol info and disable zookeeper

mojaloop/values.yaml
feat: fx-settlement-tests Removed FX_TARGET_AMOUNT as it is being set inside tests
=> feat: fx-settlement-tests Removed FX_TARGET_AMOUNT as it is being set inside tests

mojaloop/templates/NOTES.txt
Update text to indicate helm test commands only apply if the ml ttk is enabled)
Related to issue: https://github.com/mojaloop/project/issues/3149
=> chore: update text to indicate helm test commands only apply if the ml ttk is enabled
